### ISSUE TITLE
There has been an error in processing your request when analyze

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/alchemylanguage-nodejs#16]
How solved?

	cd alchemylanguage-nodejs/

	mv .env.example .env

	sudo nano .env

	##
	# Environment variables
	API_KEY=apikey
	##

**Comment by johnfelipe** [comment]
how solved this?

**Comment by germanattanasio** [comment]
If you change the api key in the `.env` file then run `npm start` and it should work.  I just tested

**Comment by johnfelipe** [comment]
is not working

http://181.135.63.86:3010/

`felipe@felipeurrego:~/alchemylanguage-nodejs$ pm2 reload server.js`
