### ISSUE TITLE
There has been the following error: 400 - Bad Request

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/alchemylanguage-nodejs#35]
http://181.135.20.181:3010/

is not working for spanish
Can i contribute for that language?

**Comment by germanattanasio** [comment]
@johnfelipe can you clarify? This code is the one we use in the demo and seems to be working fine

**Comment by johnfelipe** [comment]
i enter spanish text and not work

**Comment by kognate** [comment]
The default custom model used by the demo is english only.  You can train a custom model using WKS with spanish, but I don't know if we have a demo-able model for any language other than english.

**Comment by johnfelipe** [comment]
hi again, pls tell me if model accept spanish?
tnks

**Comment by kognate** [comment]
We do not have any prebuilt models in spanish.  You can create your own with WKS.

**Comment by germanattanasio** [comment]
As @kognate said, the demo doesn't work with Spanish text but the API has features like language identification or relationship extraction that accept Spanish. See http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/?node#typed_relations
