### ISSUE TITLE
[AlchemyLanguage-Nodejs] Page not showing correctly - Styles got weired

### ISSUE THREAD

**Issue by prasanta303** [watson-developer-cloud/alchemylanguage-nodejs#47]
I am getting issue with the page style. On running the application I am getting error as below,

**[GET / 200 37.980 ms - 63148
{ code: 404, error: 'Not Found' }
GET /css/style.css 404 37.074 ms - 32
{ code: 404, error: 'Not Found' }
GET /js/demo.js 404 45.188 ms - 32
GET /images/service-icon.svg 304 3.956 ms - -
GET /images/loading-indicator.gif 304 4.565 ms - -
GET /images/favicon.ico 200 11.241 ms - 2198
GET /images/favicon.ico 304 1.452 ms - -
{ code: 404, error: 'Not Found' }
GET /js/demo.js 404 2.029 ms - 32]**

The page which is shown is given in the attached file.
![alchemylanguage_issue](https://cloud.githubusercontent.com/assets/18462152/17021381/518794a0-4f65-11e6-9870-d7dd86fa7e50.png)

I think there is some issue in files, e.g. under public/css, public/data there is only one file namely README.md. There may be some more like this. Could you please check if those are creating problems. If not then please let me know what could be the issue in my case.

**Comment by kognate** [comment]
you should try to do an `npm install` before running `npm start` just to make sure you have all requirements installed.    I just ran this locally (though on mac os) and it worked fine.  

if you've done that and there are no errors, could you paste in the output of 

`gulp compile` in the repo?  The css assets are compiled from a gulp and this kind of problem can be fixed with a correct gulp build.

**Comment by prasanta303** [comment]
Thanks much it works.
When I run `gulp compile`, it's giving error as 
`'gulp' is not recognized as an internal or external command, operable program or batch file.`
Do I need to install Gulp in my system? If yes, let me know from where I can install it.

**Comment by kognate** [comment]
Yes, you'll need to install gulp on your system.  https://travismaynard.com/writing/getting-started-with-gulp
