### ISSUE TITLE
Issue when language not supported

### ISSUE THREAD

**Issue by walmon** [watson-developer-cloud/alchemylanguage-nodejs#61]
Hi guys, when trying spanish text, some APIs will return "unsupported-text-language" due to obvious support issues. The thing is that the EJS is not handling that escenario and breaking the rest of the API results that works.

The code to make it work (index.ejs):
[indexejs.txt](https://github.com/watson-developer-cloud/alchemylanguage-nodejs/files/462264/indexejs.txt)

**Comment by germanattanasio** [comment]
hey @walmon can you write a pull request if you know what the problem is ?

**Comment by walmon** [comment]
Hi @germanattanasio, sure, but I don't have the permissions.

**Comment by germanattanasio** [comment]
You can fork the repo do the changes there and then open a Pull Request. See https://help.github.com/articles/about-pull-requests/
