### ISSUE TITLE
A developer should be able to deploy the alchemylanguage-nodejs into Bluemix. 

### ISSUE THREAD

**Issue by bacarell** [watson-developer-cloud/alchemylanguage-nodejs#62]
Attempts to create a Bluemix application from GIT failed.   A sample of the error log is provided below.  The first readable error explains the following:

throw new Error('Argument error: api_key was not specified');

Thank you in advance.

2016-09-17T10:50:18.318-0500
[STG/0]
err
2016-09-17T10:50:32.741-0500
[STG/27]
out
-----> Uploading droplet (67M)
2016-09-17T10:50:52.102-0500
[DEA/27]
out
Starting app instance (index 0) with guid b6153bf9-d106-44bb-9c27-e2623b71cd32
2016-09-17T10:51:10.959-0500
[App/0]
out
> node server.js
2016-09-17T10:51:10.959-0500
[App/0]
out
2016-09-17T10:51:10.959-0500
[App/0]
out
> alchemy-language-demo@0.2.5 start /home/vcap/app
2016-09-17T10:51:12.000-0500
[App/0]
err
throw new Error('Argument error: api_key was not specified');
2016-09-17T10:51:12.000-0500
[App/0]
err
/home/vcap/app/node_modules/watson-developer-cloud/lib/base_service_alchemy.js:34
2016-09-17T10:51:12.001-0500
[App/0]
err
^

**Comment by germanattanasio** [comment]
did you specify the `API_KEY`?

**Comment by sachinkr2** [comment]
Please specify a API Key

**Comment by bacarell** [comment]
Hello, 

No, there was no option to do that.  You just have to click the blue 
button shown below.  I have been successful deploying apps for several 
other services. Hope this helps. 



https://github.com/watson-developer-cloud/alchemylanguage-nodejs

Kind Regards


David J. Bacarella
Watson Solution Architect
IBM Watson Group
Office: (847)805-2012
Mobile: (630)341-1140
Email: bacarell@us.ibm.com

**Comment by germanattanasio** [comment]
In Bluemix, go to the environment variables for your app and specify the Alchemy `API_KEY`. This sample doesn't create and bind the AlchemyLanguage service by default
