### ISSUE TITLE
Getting error: code=EBADCSRFTOKEN, error=invalid csrf token

### ISSUE THREAD

**Issue by prasanta303** [watson-developer-cloud/alchemylanguage-nodejs#69]
Hello,
I don't know whether this is correct place to ask. I am asking here because my try is with this application. I am trying to show alchemylanguage result in a new popup window. It's perfectly working in my local system. I deploy it in bluemix and it's opening the new page correctly. But when I clicked the "Analyze" button of popup window, it's giving error: 
**code=EBADCSRFTOKEN, error=invalid csrf token**

Application main page has a simple button, on clicking the button it opens a popup window with alchemylanguage page. But on clicking "Analyze" button it's throwing error.
New alchemyResult.ejs has been created and put in same views folder, where index.ejs present.
Only added below lines in the app.js,

> app.get('/alchemyResult',` function (req, res) {
>     res.render('alchemyResult', { ct: req._csrfToken });
> `});

It will be nice if anybody can guide me to get rid of this error.
`NOTE: alchemyResult.ejs actually contains the alchemylanguage page with java scripts and index.js simply contains a button. On clicking the button it is going to alchemylanguage result page.`

Thanks' & Regards'
Prasanta

**Comment by germanattanasio** [comment]
I disable `csrf` from the app a few days ago, you are probably using an old version
