### ISSUE TITLE
Alchemy demo en espanol

### ISSUE THREAD

**Issue by slremy** [watson-developer-cloud/alchemylanguage-nodejs#70]
It seems to me that "There has been the following error: 400 - Bad Request" isn't the expected system response for input that isn't in English. Am I wrong to think so? I'm ok with a message indicating that the corpus was trained in another langauge, but a bad request?

<img width="1193" alt="alchemylanguage" src="https://cloud.githubusercontent.com/assets/871503/23551044/48f0ed20-0025-11e7-88c5-bb1aa9735663.png">

**Comment by germanattanasio** [comment]
Hi @slremy. I think you are right. While we work on this issue, can you check the new [Natural Language Understanding](https://www.ibm.com/watson/developercloud/natural-language-understanding.html) service? It's the evolution of AlchemyLanguage.

See this demo: https://natural-language-understanding-demo.mybluemix.net

**Comment by slremy** [comment]
Thanks!
